# Simple Example of Bag Of Words


In [13]:
from sklearn.feature_extraction.text import CountVectorizer

# Define the documents
documents = [
    "The cat sat on the mat.",
    "The dog sat on the log.",
    "The cat chased the dog."
]

# Initialize the CountVectorizer
vectorizer = CountVectorizer()

# Fit the model and transform the documents into a document-term matrix
bow_matrix = vectorizer.fit_transform(documents)

# Get the feature names (vocabulary)
vocabulary = vectorizer.get_feature_names_out()

# Convert the matrix to an array and print the result
bow_array = bow_matrix.toarray()
print("Vocabulary:", vocabulary)
print("Bag of Words Matrix:\n", bow_array)


Vocabulary: ['cat' 'chased' 'dog' 'log' 'mat' 'on' 'sat' 'the']
Bag of Words Matrix:
 [[1 0 0 0 1 1 1 2]
 [0 0 1 1 0 1 1 2]
 [1 1 1 0 0 0 0 2]]


# Applications of Bag Of Words (BOW)

## Document Classification

In [17]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split

# Sample documents and their corresponding labels (e.g., spam or not spam)
documents = [
    "Win a free iPhone today!",
    "Exclusive offer just for you",
    "Dear friend, I need your help",
    "Your account has been hacked",
    "Congratulations! You've won a lottery"
]
labels = ['spam', 'spam', 'not spam', 'not spam', 'spam']

# Convert the documents into a Bag of Words model
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(documents)
y = labels

X , y


(<5x22 sparse matrix of type '<class 'numpy.int64'>'
 	with 24 stored elements in Compressed Sparse Row format>,
 ['spam', 'spam', 'not spam', 'not spam', 'spam'])

In [ ]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Train a Naive Bayes classifier on the training data
classifier = MultinomialNB()
classifier.fit(X_train, y_train)

# Predict the labels for the test data
predictions = classifier.predict(X_test)
print("Predictions:", predictions)


## Sentiment Analysis

In [15]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.linear_model import LogisticRegression

# Sample reviews and their corresponding sentiments (positive or negative)
reviews = [
    "This movie was fantastic! I loved it.",
    "Horrible movie. I hated it.",
    "The plot was boring, but the acting was good.",
    "I wouldn't recommend this movie.",
    "Definitely a must-watch!"
]
sentiments = ['positive', 'negative', 'neutral', 'negative', 'positive']

# Convert the reviews into a Bag of Words model
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(reviews)
y = sentiments

# Train a Logistic Regression classifier on the data
classifier = LogisticRegression()
classifier.fit(X, y)

# Predict the sentiment for a new review
new_review = "The movie was not bad, but it could have been better."
new_review_vectorized = vectorizer.transform([new_review])
prediction = classifier.predict(new_review_vectorized)
print("Prediction for new review:", prediction)


Prediction for new review: ['negative']
